#ifndef _APP_RADIO_H
#define _APP_RADIO_H

#define RADIO_LED	 			0x00
#define RADIO_LED_SET 			0x01
#define RADIO_LED_GET 			0x02

#define RADIO_RELAY_0	 			0x03
#define RADIO_RELAY_0_SET 			0x04
#define RADIO_RELAY_0_GET 			0x05

#define RADIO_RELAY_1	 			0x06
#define RADIO_RELAY_1_SET 			0x07
#define RADIO_RELAY_1_GET 			0x08

#define RADIO_RELAY_POWER 			0x09
#define RADIO_RELAY_POWER_SET 		0x0a
#define RADIO_RELAY_POWER_GET 		0x0b

#define RADIO_PIR			 		0x0c
#define RADIO_FLOOD_DETECTOR		0x0d

#define RADIO_ACCELEROMETER_ALERT			0x0e
#define RADIO_ACCELEROMETER_ACCELERATION	0x0f

#define RADIO_LED_STRIP_COLOR_SET 		0x10
#define RADIO_LED_STRIP_BRIGHTNESS_SET 	0x11
#define RADIO_LED_STRIP_COMPOUND_SET 	0x12
#define RADIO_LED_STRIP_EFFECT_SET 	    0x13
#define RADIO_LED_STRIP_THERMOMETER_SET 0x14

#define RADIO_LCD_BUTTON_LEFT		0x20
#define RADIO_LCD_BUTTON_RIGHT		0x21

#define RADIO_ENCODER_INCREMENT     0x30
#define RADIO_MAGNET_SWITCH_STATE   0x31


#define RADIO_THERMOSTAT_SET_POINT_TEMPERATURE 0xf0

// TYPE

#define RADIO_LED_STRIP_EFFECT_TYPE_TEST					0x00
#define RADIO_LED_STRIP_EFFECT_TYPE_RAINBOW					0x01
#define RADIO_LED_STRIP_EFFECT_TYPE_RAINBOW_CYCLE			0x02
#define RADIO_LED_STRIP_EFFECT_TYPE_THEATER_CHASE_RAINBOW	0x03
#define RADIO_LED_STRIP_EFFECT_TYPE_COLOR_WIPE				0x04
#define RADIO_LED_STRIP_EFFECT_TYPE_THEATER_CHASE			0x05

#define RADIO_CHANNEL_A 0x00
#define RADIO_CHANNEL_B 0x80


#endif /* APP_RADIO_H_ */
