#ifndef _APP_RADIO_H
#define _APP_RADIO_H

#define RADIO_ACCELEROMETER_ACCELERATION	0x0f

#define RADIO_LED_STRIP_COLOR_SET 		0x10
#define RADIO_LED_STRIP_BRIGHTNESS_SET 	0x11
#define RADIO_LED_STRIP_COMPOUND_SET 	0x12
#define RADIO_LED_STRIP_EFFECT_SET 	    0x13
#define RADIO_LED_STRIP_THERMOMETER_SET 0x14

#define RADIO_LCD_TEXT_SET          0x22
#define RADIO_LCD_SCREEN_CLEAR      0x23

#define RADIO_RELAY_0_PULSE_SET   0x32
#define RADIO_RELAY_1_PULSE_SET   0x33

// TYPE

#define RADIO_LED_STRIP_EFFECT_TYPE_TEST					0x00
#define RADIO_LED_STRIP_EFFECT_TYPE_RAINBOW					0x01
#define RADIO_LED_STRIP_EFFECT_TYPE_RAINBOW_CYCLE			0x02
#define RADIO_LED_STRIP_EFFECT_TYPE_THEATER_CHASE_RAINBOW	0x03
#define RADIO_LED_STRIP_EFFECT_TYPE_COLOR_WIPE				0x04
#define RADIO_LED_STRIP_EFFECT_TYPE_THEATER_CHASE			0x05

#define RADIO_CHANNEL_A 0x00
#define RADIO_CHANNEL_B 0x80


#endif /* APP_RADIO_H_ */
